# Making GUI for Deskop Assistant 

import tkinter as tk
root = tk.Tk()
Height = 600
Width = 800
bg = tk.PhotoImage(file = "SeekPng.com_minions-png_176959.png")
label1 = tk.Label(root, image = bg)
label1.place(x = 0, y = 0)
canvas = tk.Canvas(root, heigh = Height, width= Width)
canvas.pack()
frame = tk.Frame(root, bg = '#80c1ff')
frame.place(relx = 0.05,rely = 0.05, relwidth=0.8, relheight=0.06)
button_t = tk.Button(frame, text= 'TIME', command = lambda: time())
button_t.place(relx= 0.005, rely=0.06, relwidth=0.1, relheight=0.88)
label_t = tk.Label(frame, font = 40, text = '--/--/--')
label_t.place(relx= 0.2, rely=0.06, relwidth=0.797, relheight=0.88)
frame_1 = tk.Frame(root, bg = 'yellow')
frame_1.place(relx = 0.05,rely = 0.15, relwidth=0.8, relheight=0.06)
button_d = tk.Button(frame_1, text= 'Date',command = lambda: date_1())
button_d.place(relx= 0.005, rely=0.06, relwidth=0.1, relheight=0.88)
label_d = tk.Label(frame_1, font = 40, text = '--/--/--')
label_d.place(relx= 0.2, rely=0.06, relwidth=0.797, relheight=0.88)
frame_2 = tk.Frame(root, bg = 'pink')
frame_2.place(relx = 0.05,rely = 0.25, relwidth=0.8, relheight=0.06)
button_w = tk.Button(frame_2, text= 'Weather', command= lambda: We_ge(entry.get()))
button_w.place(relx= 0.005, rely=0.06, relwidth=0.1, relheight=0.88)
entry = tk.Entry(frame_2, font = 40)
entry.place(relx= 0.2, rely=0.06, relwidth=0.797, relheight=0.88)
frame_3 = tk.Frame(root, bg = 'green')
frame_3.place(relx = 0.05,rely = 0.35, relwidth=0.8, relheight=0.45)
label_w = tk.Label(frame_3, font = 40, text = 'Hi I am Bob. I can help you with\t\t\n1) Opening and Searching on Google\n  2) Opening and Searching on Youtube\n\t    3)Playing Muic\t\t\t\t\n    4)Searching Wikipedia\t\t\n    5)Telling time at your place\t\t\n    6)Searcing Weathe\t\t\n To close me you can just say [Close Bob]')
label_w.place(relx= 0.05, rely=0.1, relwidth=0.45, relheight=0.8)
label_g = tk.Label(frame_3, font = 40)
label_g.place(relx= 0.53, rely=0.1, relwidth=0.45, relheight=0.8)
frame_4 = tk.Frame(root, bg = 'black')
frame_4.place(relx = 0.05,rely = 0.85, relwidth=0.8, relheight=0.09)
button_1 = tk.Button(frame_4, text = 'Start', font= 40, command= lambda: start())
button_1.place(relx = 0.05,rely = 0.25, relwidth=0.15, relheight=0.45)
root.mainloop()